extends Node

var card_images = [
	"res://Cards/Images/2s.png",
	"res://Cards/Images/3s.png",
	"res://Cards/Images/4s.png",
	"res://Cards/Images/5s.png",
	"res://Cards/Images/6s.png",
	"res://Cards/Images/7s.png",
	"res://Cards/Images/8s.png",
	"res://Cards/Images/9s.png",
	"res://Cards/Images/10s.png",
	"res://Cards/Images/njs.png",
	"res://Cards/Images/nqs.png",
	"res://Cards/Images/nks.png",
	"res://Cards/Images/nas.png",
	"res://Cards/Images/2h.png",
	"res://Cards/Images/3h.png",
	"res://Cards/Images/4h.png",
	"res://Cards/Images/5h.png",
	"res://Cards/Images/6h.png",
	"res://Cards/Images/7h.png",
	"res://Cards/Images/8h.png",
	"res://Cards/Images/9h.png",
	"res://Cards/Images/10h.png",
	"res://Cards/Images/jh.png",
	"res://Cards/Images/qh.png",
	"res://Cards/Images/kh.png",
	"res://Cards/Images/ah.png",
	"res://Cards/Images/2d.png",
	"res://Cards/Images/3d.png",
	"res://Cards/Images/4d.png",
	"res://Cards/Images/5d.png",
	"res://Cards/Images/6d.png",
	"res://Cards/Images/7d.png",
	"res://Cards/Images/8d.png",
	"res://Cards/Images/9d.png",
	"res://Cards/Images/10d.png",
	"res://Cards/Images/jd.png",
	"res://Cards/Images/qd.png",
	"res://Cards/Images/kd.png",
	"res://Cards/Images/ad.png",
	"res://Cards/Images/2c.png",
	"res://Cards/Images/3c.png",
	"res://Cards/Images/4c.png",
	"res://Cards/Images/5c.png",
	"res://Cards/Images/6c.png",
	"res://Cards/Images/7c.png",
	"res://Cards/Images/8c.png",
	"res://Cards/Images/9c.png",
	"res://Cards/Images/10c.png",
	"res://Cards/Images/jc.png",
	"res://Cards/Images/qc.png",
	"res://Cards/Images/kc.png",
	"res://Cards/Images/ac.png"
]


var card_values = {
	"res://Cards/Images/2s.png": 2,
	"res://Cards/Images/3s.png": 3,
	"res://Cards/Images/4s.png": 4,
	"res://Cards/Images/5s.png": 5,
	"res://Cards/Images/6s.png": 6,
	"res://Cards/Images/7s.png": 7,
	"res://Cards/Images/8s.png": 8,
	"res://Cards/Images/9s.png": 9,
	"res://Cards/Images/10s.png": 10,
	"res://Cards/Images/njs.png": 11,
	"res://Cards/Images/nqs.png": 12,
	"res://Cards/Images/nks.png": 13,
	"res://Cards/Images/nas.png": 14,
	"res://Cards/Images/2h.png": 2,
	"res://Cards/Images/3h.png": 3,
	"res://Cards/Images/4h.png": 4,
	"res://Cards/Images/5h.png": 5,
	"res://Cards/Images/6h.png": 6,
	"res://Cards/Images/7h.png": 7,
	"res://Cards/Images/8h.png": 8,
	"res://Cards/Images/9h.png": 9,
	"res://Cards/Images/10h.png": 10,
	"res://Cards/Images/jh.png": 11,
	"res://Cards/Images/qh.png": 12,
	"res://Cards/Images/kh.png": 13,
	"res://Cards/Images/ah.png": 14,
	"res://Cards/Images/2d.png": 2,
	"res://Cards/Images/3d.png": 3,
	"res://Cards/Images/4d.png": 4,
	"res://Cards/Images/5d.png": 5,
	"res://Cards/Images/6d.png": 6,
	"res://Cards/Images/7d.png": 7,
	"res://Cards/Images/8d.png": 8,
	"res://Cards/Images/9d.png": 9,
	"res://Cards/Images/10d.png": 10,
	"res://Cards/Images/jd.png": 11,
	"res://Cards/Images/qd.png": 12,
	"res://Cards/Images/kd.png": 13,
	"res://Cards/Images/ad.png": 14,
	"res://Cards/Images/2c.png": 2,
	"res://Cards/Images/3c.png": 3,
	"res://Cards/Images/4c.png": 4,
	"res://Cards/Images/5c.png": 5,
	"res://Cards/Images/6c.png": 6,
	"res://Cards/Images/7c.png": 7,
	"res://Cards/Images/8c.png": 8,
	"res://Cards/Images/9c.png": 9,
	"res://Cards/Images/10c.png": 10,
	"res://Cards/Images/jc.png": 11,
	"res://Cards/Images/qc.png": 12,
	"res://Cards/Images/kc.png": 13,
	"res://Cards/Images/ac.png": 14
}

var stats = {
	"MHP": 100,
	"HP": 100,
	"strength": 1,
	"Nvp": 10,
	"Lvl": 1,
	"EXP": 0,
	"deck": [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15,0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15,0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15,0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15,]
}

var dealer = {
	"MHP": 100,
	"HP": 100,
	"MinNvp": 10,
	"MaxNvp": 30,
	"Minexp": 120,
	"Maxexp": 300,
	"deck": [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51]
}
