extends Node

var stats = {
	"MHP": 100,
	"HP": 100,
	"Nvp": 10,
	"strength": 1,
	"bt": [],
	"Lvl": 1,
	"EXP": 1
}
var dealer = {
	"MHP": 100,
	"HP": 100,
	"MinNvp": 10,
	"MaxNvp": 30,
	"Minexp": 120,
	"Maxexp":300,
	"deck": [],
}



var card_images = [
	"res://Cards/Images/Norm 2 Spades.png",
	"res://Cards/Images/N5S.png",
	"res://Cards/Images/N9S.png",
	"res://Cards/Images/5s.png",
	"res://Cards/Images/n10h.png",
	"res://Cards/Images/n5h.png",
	"res://Cards/Images/n9h.png",
	"res://Cards/Images/3d.png",
	"res://Cards/Images/N6S.png",
	"res://Cards/Images/n4h.png",
	"res://Cards/Images/n4d.png",
	"res://Cards/Images/nqs.png",
	"res://Cards/Images/nkc.png",
	"res://Cards/Images/N8S.png",
	"res://Cards/Images/n3c.png",
	"res://Cards/Images/n10s.png",
	"res://Cards/Images/nAs.png",
	"res://Cards/Images/9h.png",
	"res://Cards/Images/n10d.png",
	"res://Cards/Images/ah.png",
	"res://Cards/Images/3h.png",
	"res://Cards/Images/norm 3 spades.png",
	"res://Cards/Images/4s.png",
	"res://Cards/Images/jd.png",
	"res://Cards/Images/4h.png",
	"res://Cards/Images/n3d.png",
	"res://Cards/Images/n7h.png",
	"res://Cards/Images/n2d.png",
	"res://Cards/Images/n8h.png",
	"res://Cards/Images/n5c.png",
	"res://Cards/Images/n10c.png",
	"res://Cards/Images/2nh.png",
	"res://Cards/Images/n9d.png",
	"res://Cards/Images/jc.png",
	"res://Cards/Images/6s.png",
	"res://Cards/Images/3s.png",
	"res://Cards/Images/nkd.png",
	"res://Cards/Images/kh.png",
	"res://Cards/Images/n4c.png",
	"res://Cards/Images/9s.png",
	"res://Cards/Images/nkh.png",
	"res://Cards/Images/n2c.png",
	"res://Cards/Images/n7s.png",
	"res://Cards/Images/n7d.png",
	"res://Cards/Images/N4S.png",
	"res://Cards/Images/njH.png",
	"res://Cards/Images/6d.png",
	"res://Cards/Images/10c.png",
	"res://Cards/Images/2d.png",
	"res://Cards/Images/6h.png",
	"res://Cards/Images/8c.png",
	"res://Cards/Images/7d.png",
	"res://Cards/Images/8h.png",
	"res://Cards/Images/2c.png",
	"res://Cards/Images/js.png",
	"res://Cards/Images/7c.png",
	"res://Cards/Images/njc.png",
	"res://Cards/Images/2s.png",
	"res://Cards/Images/6c.png",
	"res://Cards/Images/njD.png",
	"res://Cards/Images/7s.png",
	"res://Cards/Images/8s.png",
	"res://Cards/Images/nah.png",
	"res://Cards/Images/nac.png",
	"res://Cards/Images/nks.png",
	"res://Cards/Images/3c.png",
	"res://Cards/Images/nqc.png",
	"res://Cards/Images/n5d.png",
	"res://Cards/Images/ad.png",
	"res://Cards/Images/n9c.png",
	"res://Cards/Images/10d.png",
	"res://Cards/Images/as.png",
	"res://Cards/Images/5d.png",
	"res://Cards/Images/kc.png"
]

var card_values = {
	"res://Cards/Images/Norm 2 Spades.png": 2,
	"res://Cards/Images/N5S.png": 5,
	"res://Cards/Images/N9S.png": 9,
	"res://Cards/Images/5s.png": 5,
	"res://Cards/Images/n10h.png": 10,
	"res://Cards/Images/n5h.png": 5,
	"res://Cards/Images/n9h.png": 9,
	"res://Cards/Images/3d.png": 3,
	"res://Cards/Images/N6S.png": 6,
	"res://Cards/Images/n4h.png": 4,
	"res://Cards/Images/n4d.png": 4,
	"res://Cards/Images/nqs.png": 12,
	"res://Cards/Images/nkc.png": 13,
	"res://Cards/Images/N8S.png": 8,
	"res://Cards/Images/n3c.png": 3,
	"res://Cards/Images/n10s.png": 10,
	"res://Cards/Images/nAs.png": 14,
	"res://Cards/Images/9h.png": 9,
	"res://Cards/Images/n10d.png": 10,
	"res://Cards/Images/ah.png": 14,
	"res://Cards/Images/3h.png": 3,
	"res://Cards/Images/norm 3 spades.png": 3,
	"res://Cards/Images/4s.png": 4,
	"res://Cards/Images/jd.png": 11,
	"res://Cards/Images/4h.png": 4,
	"res://Cards/Images/n3d.png": 3,
	"res://Cards/Images/n7h.png": 7,
	"res://Cards/Images/n2d.png": 2,
	"res://Cards/Images/n8h.png": 8,
	"res://Cards/Images/n5c.png": 5,
	"res://Cards/Images/n10c.png": 10,
	"res://Cards/Images/2nh.png": 2,
	"res://Cards/Images/n9d.png": 9,
	"res://Cards/Images/jc.png": 11,
	"res://Cards/Images/6s.png": 6,
	"res://Cards/Images/ncb.png": 0,
	"res://Cards/Images/3s.png": 3,
	"res://Cards/Images/nkd.png": 13,
	"res://Cards/Images/kh.png": 13,
	"res://Cards/Images/n4c.png": 4,
	"res://Cards/Images/9s.png": 9,
	"res://Cards/Images/nkh.png": 13,
	"res://Cards/Images/n2c.png": 2,
	"res://Cards/Images/n7s.png": 7,
	"res://Cards/Images/n7d.png": 7,
	"res://Cards/Images/N4S.png": 4,
	"res://Cards/Images/njH.png": 11,
	"res://Cards/Images/6d.png": 6,
	"res://Cards/Images/10c.png": 10,
	"res://Cards/Images/2d.png": 2,
	"res://Cards/Images/6h.png": 6,
	"res://Cards/Images/8c.png": 8,
	"res://Cards/Images/7d.png": 7,
	"res://Cards/Images/8h.png": 8,
	"res://Cards/Images/2c.png": 2,
	"res://Cards/Images/js.png": 11,
	"res://Cards/Images/7c.png": 7,
	"res://Cards/Images/njc.png": 11,
	"res://Cards/Images/2s.png": 2,
	"res://Cards/Images/6c.png": 6,
	"res://Cards/Images/njD.png": 11,
	"res://Cards/Images/7s.png": 7,
	"res://Cards/Images/8s.png": 8,
	"res://Cards/Images/nah.png": 14,
	"res://Cards/Images/nac.png": 14,
	"res://Cards/Images/nks.png": 13,
	"res://Cards/Images/3c.png": 3,
	"res://Cards/Images/nqc.png": 12,
	"res://Cards/Images/n5d.png": 5,
	"res://Cards/Images/ad.png": 14,
	"res://Cards/Images/n9c.png": 9,
	"res://Cards/Images/10d.png": 10,
	"res://Cards/Images/as.png": 14,
	"res://Cards/Images/5d.png": 5,
	"res://Cards/Images/kc.png": 13
}
